import "oaidl.idl";
import "ocidl.idl";

[
  uuid(81512E3A-54CE-47C2-B857-0389A518CC37),
  version(1.0),
  helpstring("se_win 1.0 Type Library")
]
library se_winLib
{
  importlib("stdole32.tlb");
  importlib("stdole2.tlb");
  // import Solid Edge types
  importlib("framewrk.tlb");

  [ hidden, uuid(480265A4-4782-4B95-88C7-FF01108567F3) ]
  coclass SE_WINAddInEventsEx
  {
    [default] interface ISEAddInEventsEx;
  }

  [ hidden, uuid(BE38AD96-88BA-4591-A0E3-F4302C67EEAA) ]
  coclass SE_WINAddInEvents
  {
    [default] interface ISEAddInEvents;
  }

  [ hidden, uuid(B1A849C5-0D80-4809-8B20-4401008DF1F7) ]
  coclass SE_WINApplicationEvents
  {
    [default] interface IUnknown;
  }

  [ hidden, uuid(3E6832A8-2327-41C3-81AA-31C650DCC8AE) ]
  coclass SE_WINAddInEdgeBarEvents
  {
    [default] interface ISEAddInEdgeBarEvents;
  }

  [ hidden, uuid(3B4C3924-CD93-4DE8-B853-3963FAFFD48A) ]
  coclass Commands
  {
    [default] interface IUnknown;
  }

  [ hidden, uuid(B564A558-0E46-49A2-A217-6A3BED18675F) ]
  coclass SE_WINCommand
  {
    [default] interface IUnknown;
  }

  [ hidden, uuid(47F753B0-1579-4E8D-BE40-A6289FF0476C) ]
  coclass CommandEvents
  {
    [default] interface ISECommandEvents;
  }

  [ hidden, uuid(F91C02C0-3BEE-4520-899A-5F064DFE4816) ]
  coclass MouseEvents
  {
    [default] interface ISEMouseEvents;
  }

  [hidden, uuid(6BF77CBC-DC14-42DA-82C0-17E2D1F5AE25) ]
  coclass LocateFilterEvents
  {
    [default] interface ISELocateFilterEvents;
  }

  [ hidden, uuid(BEAB7201-2F6B-4F9F-9603-B5B8FBD7EEA0) ]
  coclass CommandWindowEvents
  {
    [default] interface ISECommandWindowEvents;
  }

  [ hidden, uuid(C3E88B7B-C30E-4846-94F0-F8BF9E00978F) ]
  coclass ADDINDocument
  {
    [default] interface IUnknown;
  }

  [ hidden, uuid(10ECC468-25CB-42E1-BFF1-A662E9B61B52) ]
  coclass ADDINDocumentEvents
  {
    [default] interface ISEDocumentEvents;
  }
};
